### PR TITLE
txHandler: fix TestTxHandlerAppRateLimiter

### LINKED ISSUE #5972: Buggy test?
Shouldn't this be `tx2.Sign` instead of `tx.Sign`

https://github.com/algorand/go-algorand/blob/0e7087bb75efb14fe0d03009212a8c1111014102/data/txHandler_test.go#L2673

The resulting txn has an empty `ForeignApps`, and the txn gets dropped by the `handler.msgCache` instead of the `handler.appLimiter`

### PR DESCRIPTION
**Pull request by algorandskiy**
## Summary

As discovered in https://github.com/algorand/go-algorand/issues/5972 the TestTxHandlerAppRateLimiter had a typo.
This PR fixed it by crafting workload to make sure ARL in txHandler is getting actually called.

While debugging I noticed that `maxBucketSize` is set to 1 if `TxBacklogAppTxRateLimiterMaxSize` is less than 128 (number of buckets). Although this was not an issue in production due to `TxBacklogAppTxRateLimiterMaxSize=1048576` it would trigger eviction on each insert that makes ARL noop. Setting `maxBucketSize` to 2 as its min value makes it working in such extreme configuration.

## Test Plan

This is a test fix

Closes #5972

### CODE REVIEW

File: data/txHandler_test.go [hunk 1]
```diff
@@ -2667,21 +2673,21 @@ func TestTxHandlerAppRateLimiter(t *testing.T) {
...
+	counterBefore := transactionMessagesAppLimiterDrop.GetUint64Value()
 	// trigger the rate limiter and ensure the txn is ignored
-	tx2 := tx
-	for i := 0; i < cfg.TxBacklogAppTxPerSecondRate*cfg.TxBacklogServiceRateWindowSeconds; i++ {
-		tx2.ForeignApps = append(tx2.ForeignApps, 1)
+	numTxnToTriggerARL := cfg.TxBacklogAppTxPerSecondRate * cfg.TxBacklogServiceRateWindowSeconds
+	for i := 0; i < numTxnToTriggerARL; i++ {
+		tx2 := tx
+		tx2.Header.Sender = addresses[i+1]
+		signedTx2 := tx2.Sign(secrets[i])
```
Comment (jasonpaulos) [inline data/txHandler_test.go:2682]: Why not use `secrets[i+1]`? Is this so that the txn will be invalid and ignored? If so, would be good to document this

File: data/txHandler_test.go [hunk 2]
```diff
@@ -2667,21 +2673,21 @@ func TestTxHandlerAppRateLimiter(t *testing.T) {
...
-	action = handler.processIncomingTxn(network.IncomingMessage{Data: blob2, Sender: mockSender{}})
-	require.Equal(t, network.OutgoingMessage{Action: network.Ignore}, action)
-	require.Equal(t, 1, len(handler.backlogQueue))
-
-	// backlogQueue has the first txn, but the second one is dropped
-	msg := <-handler.backlogQueue
-	require.Equal(t, msg.rawmsg.Data, blob, blob)
+	// last txn should be dropped
+	require.Equal(t, 1+numTxnToTriggerARL-1, len(handler.backlogQueue))
+	require.Equal(t, counterBefore+1, transactionMessagesAppLimiterDrop.GetUint64Value())
```
Comment (jasonpaulos) [inline data/txHandler_test.go:2690]: This is a parellel test. Are you concerned about using a global metric counter for this?

File: data/txHandler_test.go (hunk 1 above)
Comment (algorandskiy) [reply data/txHandler_test.go:2682]: it does not matter since we are not validating txns in this case but it is another copy-paste error. Fixed

File: data/txHandler_test.go (hunk 2 above)
Comment (algorandskiy) [reply data/txHandler_test.go:2690]: true, better not to. fixed

**Review by jasonpaulos — APPROVED** [review]
