### PR TITLE
avm: fix teal disassembly for deadcode

### LINKED ISSUE #6489: Unable to reassemble a disassembled program that contains unused subroutines
@dragmz identified an unusual issue where some existing smart contracts were unable to be assmbled after being disassembled.

The two application IDs originally identified as having this problem were: `2747284875` and `2309798439`.

After a little investigating I discovered that during disassembly, any unused subroutines/labels doesn't get given a label. Which should be fine since labels are there for us humans, and any branch/call opcode is actually using a signed int16 offset.

The problem however, is when an unused subroutine uses the `proto` opcode. This results in any use of `frame_dig` or `frame_bury` now being globally scoped and these errors being produced.

### Example:

Using one of the existing programs.

```
% curl -s https://mainnet-api.algonode.cloud/v2/applications/2747284875 \
| jq -r '.params."approval-program"' \
| base64 -d \
| goal clerk compile -D - \
| goal clerk compile -

-: 829: itxn_field AssetReceiver arg 0 wanted type address got uint64
-: 834: itxn_field AssetAmount arg 0 wanted type uint64 got []byte
-: 839: itxn_field XferAsset arg 0 wanted type uint64 got []byte
-: 859: itxn_field AssetReceiver arg 0 wanted type address got uint64
-: 864: itxn_field AssetAmount arg 0 wanted type uint64 got []byte
-: 869: itxn_field XferAsset arg 0 wanted type uint64 got []byte
-: 6 errors
```

### MRE

This program will happily compile and deploy. But disassembling it results in the "unusedSubroutine" label being omitted.

```
#pragma version 12

callsub usedSubroutine
pushint 1
return

usedSubroutine:
  retsub

unusedSubroutine:
  proto 0 0

  pushint 0
  pushint 1
  frame_bury 0
  pop

  retsub
```
Assemble + Disassemble: Label not given to unusedSubroutine
```
% goal clerk compile test.teal -o - \
| goal clerk compile -D -

#pragma version 12
callsub label1
pushint 1
return
label1:
retsub
proto 0 0     // <--- no label
pushint 0
pushint 1
frame_bury 0
pop
retsub
```
Assemble + Dissasmble + Assemble: Errors
```
% goal clerk compile test.teal -o - \
| goal clerk compile -D - \
| goal clerk compile -

-: 1 error: 10: frame_bury above stack
-: 1 error: 10: frame_bury above stack
```

If you comment out the `usedSubroutine` all together, you'll get a different error: `proto must be unreachable from previous PC`.

```
% goal clerk compile test.teal -o - \
| goal clerk compile -D - \
| goal clerk compile -

-: 1 error: 4: proto must be unreachable from previous PC
-: 1 error: 4: proto must be unreachable from previous PC
```

### PR DESCRIPTION
**Pull request by nullun**
## Summary

This PR partially fixes #6489, as I believe there are actually two separate issues.

1. Subroutines that are never called (deadcode) don't receive a label when disassembled. So attempting to reassemble them can result in various errors:
    - `proto must be unreachable from previous PC`
    - `frame_bury above stack`
    - `frame_dig above stack`

(I'll follow up with a PR on the second issue in the future)

This PR addresses deadcode. Disassembling a program with unreachable subroutines will now give labels to those subroutines.

## Test Plan

Included a test for the change. Running the test on master currently fails with a expected error. It succeeds on the current branch.
 - `TestDisassembleDeadSubroutine`

### CODE REVIEW

File: data/transactions/logic/assembler_test.go [hunk 1]
```diff
@@ -2216,6 +2216,145 @@ label1:
...
+	// slot with an address via frame_bury, then reads the slot with frame_dig
+	// and adds 1. The fall-through path narrows the slot to address, so
+	// without type widening at the label, + rejects the frame_dig result.
+	//
+	// Equivalent source (rejected by this assembler's type checker):
+	//   #pragma version 8
+	//   pushint 1; callsub label1; return
+	//   label1: proto 1 1; pushint 0; frame_dig -1
+	//   bz label2; global ZeroAddress; frame_bury 0
+	//   label2: frame_dig 0; pushint 1; +; retsub
```
Comment (jannotti) [inline data/transactions/logic/assembler_test.go]: You can use `#pragma typetrack false` to prevent typetracking, which should let you present the program nicely in the test.

File: data/transactions/logic/assembler_test.go [hunk 2]
```diff
@@ -2216,6 +2216,145 @@ label1:
...
+		0x81, 0x00,             // pushint 0
+		0x41, 0x00, 0x06,       // bz +6 → load 0
+		0x80, 0x02, 0x68, 0x69, // pushbytes "hi"
+		0x35, 0x00,             // store 0
+		0x34, 0x00,             // load 0
+		0x81, 0x01,             // pushint 1
+		0x08,                   // +
+		0x48,                   // pop
+		0x81, 0x01,             // pushint 1
+	}
```
Comment (jannotti) [inline data/transactions/logic/assembler_test.go]: I am not convinced this should compile.  The path that goes through `pushbytes` is _always_ wrong.  Yes, it is conceivable there is a path hits the `push` (by going through the label1 after having stored an int) and that path is ok. 
But there is a path that is definitely wrong.  Is this showing up in real code?

**Comment by algorandskiy** [comment]
I'm wiling to take commit 1 (dead proto blocks)

File: data/transactions/logic/assembler_test.go (hunk 2 above)
Comment (nullun) [reply data/transactions/logic/assembler_test.go]: I've had another look into this and focused on the real-world code which is running into it. I've found 157 contracts on Mainnet that can be disassembled but not reassembled due to it. I suspect it'll require further discussion, so for this PR I'll revert the second commit and just keep it focused on the deadcode labels. I'll include the new PR here once I've opened it.

Comment (jannotti) [reply data/transactions/logic/assembler_test.go]: It wouldn't be crazy to emit the `#pragme typetrack false` for programs that disassemble and really don't typecheck.

Comment (nullun) [reply data/transactions/logic/assembler_test.go]: That's an idea, I hadn't thought about adding it in automatically during disassembly. I have just updated the [original issue](https://github.com/algorand/go-algorand/issues/6489#issuecomment-4260798130), and came to a similar view that a user _could_ just add that line themselves to get it to work.

**Review by algorandskiy — APPROVED** [review]

**Review by jannotti — APPROVED** [review]
