### PR TITLE
catchup: improve classBasedPeerSelector on small peer sets

### LINKED ISSUE #6152: Catchup over P2P stops intermittently
### Subject of the issue

If a node is configured as pure P2P (e.g. `"EnableP2P": true` and `"EnableDHTProviders": true`) then normal catchup will advance a several hundred rounds, then pause for a few seconds. Fast catchup works as expected. However, once fast catchup completes, the same behavior is observed for regular catchup until caught up.

### Your environment

* Software version: 3.26.0.stable [rel/stable] (commit #0d10b244)
* Operating System details: Mac OS X 15.0.1 (Sequoia) Apple M1 Pro

### Steps to reproduce

1. Use above config settings to set up a P2P node
2. Start a regular catchup

### Expected behaviour

Normal speed catchup, without pauses

### Actual behaviour

As above - proceed several hundred rounds, then pause for a few seconds, over and over.

### PR DESCRIPTION
**Pull request by algorandskiy**
## Summary

Per #6152 there was an issue with catchup on P2P networks that ended up to be a peer selector (`classBasedPeerSelector`) issue. Suppose there are only two Relays and no Archival nodes, and only one of the relays have all the blocks, and a node in question does not have DHT enabled. In this case it will only get `ConnectedOut` and `PhonebookRelay` peers (that are the same) and attempts to catchup from them. The following will happen:
1. A relay without old blocks will be randomly selected and after couple of failures gets down ranked below a relay with blocks ( exact rank number is 3 but it does not really matter)
2. Then the second relay get selected and about a hundred blocks get downloaded from it (exact number is 79 until its rank reaches 3, see below)
3. `peerSelector` has a special logic to penalize a node as it is used in order to distribute load more evenly.
4. After that the first node is selected again, fails, and the steps 2-3 repeat.
5. Next, the `classBasedPeerSelector` instance determines `ConnectedOut` class had too many failures, and it is time to temporary disable this class. It advances to `PhonebookRelay` and the process repeats.
6. Then this class gets banned as well, and no peers in remaining classes.
7. Catchup service runs out of peers and exits until it resumes in 17 (`agreement.defaultDeadlineTimeout`) seconds again.

Fixed by decrementing failures counter in `classBasedPeerSelector` so that a single failing node does not prevent the entire class to give up on - the underlying `peerSelector` will punish it harder and harder until its rank passes the usage saturation bound (rank=23 for more context).

Additionally:
1. Made `rankSamples` a linked list with node reusage instead of a slice => no extra mem allocs on long catchups.
2. Fixed some types and uniformed `fetchAndWrite` logging. 

Peer selector / catchup updates:
1. History intro https://github.com/algorand/go-algorand/pull/2060
2. Better 404 handling https://github.com/algorand/go-algorand/pull/5809
3. Class based peer selector to support archival role https://github.com/algorand/go-algorand/pull/5937

Closes #6152

## Test Plan

1. Updated a unit test
11. Run a local net catchup before and after the fix

### CODE REVIEW

File: catchup/classBasedPeerSelector.go [hunk 1]
```diff
@@ -58,6 +59,9 @@ func (c *classBasedPeerSelector) rankPeer(psp *peerSelectorPeer, rank int) (int,
 		// Peer was in this class, if there was any kind of download issue, we increment the failure count
 		if rank >= peerRankNoBlockForRound {
 			wp.downloadFailures++
+		} else if wp.downloadFailures > 0 {
+			// class usually multiple peers and we do not want to punish the entire class for one peer's failure
+			wp.downloadFailures--
```
Comment (gmalouf) [inline catchup/classBasedPeerSelector.go:64]: Basically, somebody did something right so lets not penalize as heavily...I do wonder if it should be 1 for 1 or more like 1 failure vs a few successes to revert...but that adds complexity too.

File: catchup/classBasedPeerSelector_test.go [hunk 2]
```diff
@@ -481,6 +482,7 @@ func TestClassBasedPeerSelector_integration(t *testing.T) {
 	require.Nil(t, err)
 	require.Equal(t, mockP1WrappedPeer, peerResult)
 	cps.rankPeer(mockP1WrappedPeer, peerRankNoBlockForRound)
+	cps.rankPeer(mockP1WrappedPeer, peerRankNoBlockForRound)
```
Comment (gmalouf) [inline catchup/classBasedPeerSelector_test.go:485]: why was this extra one needed?

File: catchup/classBasedPeerSelector.go (hunk 1 above)
Comment (jannotti) [reply catchup/classBasedPeerSelector.go:64]: How about:
```
success := rank < peerRankNoBlockForRound
if success {
   wp.downloadFailures = max(wp.downloadFailures-1, 0)
} else {
   wp.downloadFailures++
}
```
I think that's a clearer way of showing downloadFailures goes up for failures, down for success.

**Review by jannotti — DISMISSED** [review]
I made a suggestion, but ready to approve even if you don't like it!

File: catchup/peerSelector.go [hunk 3]
```diff
@@ -233,12 +234,6 @@ func (hs *historicStats) push(value int, counter uint64, class peerClass) (avera
 		return value
 	}
 
-	// This is a moving window. Remore the least recent value once the window is full
```
Comment (gmalouf) [inline catchup/peerSelector.go:236]: I guess we did not use this in the switch, so okay to move below

**Review by gmalouf — DISMISSED** [review]
Sprinkle of comments, but this looks good to me.

File: catchup/classBasedPeerSelector_test.go (hunk 2 above)
Comment (algorandskiy) [reply catchup/classBasedPeerSelector_test.go:485]: in the test above there are 3 failures, one success so need to counter this success with one more failure:
```golang
	oldRank, newRank = cps.rankPeer(mockP1WrappedPeer, peerRankNoBlockForRound)
...
	durationRank = cps.peerDownloadDurationToRank(mockP1WrappedPeer, 500)
	oldRank, newRank = cps.rankPeer(mockP1WrappedPeer, durationRank)
```

File: catchup/classBasedPeerSelector.go (hunk 1 above)
Comment (algorandskiy) [reply catchup/classBasedPeerSelector.go]: > I do wonder if it should be 1 for 1 or more like 1 failure vs a few successes to revert...but that adds complexity too.

we have a similar logic in history tracking in `peerSelector`, so I guess it is fine
```golang
		if hs.downloadFailures > 0 {
			hs.downloadFailures--
		}
```

> I think that's a clearer way of showing downloadFailures goes up for failures, down for success.

thanks, applied a slight variation with `failure := rank >= peerRankNoBlockForRound`

**Review by gmalouf — APPROVED** [review]

**Review by jannotti — APPROVED** [review]
