### PR TITLE
network: fix outgoing HTTP rate limiting

### LINKED ISSUE #6117: Catchup regression after p2p merge due to rate limiting
### Subject of the issue

Requests for blocks in normal catchup are triggering rate limiting. This results in slow catchup performance and repeated pauses.

Note that this behavior starts with the p2p merge `c8407abc` #5939. A binary built from the immediately preceding commit `63c0d5bd` does not have this problem.

### Your environment

* Software version: 3.26.2066.nightly [rel/nightly] (commit #9364f13b)
* In this particular case, running on DevNet
* Replicated on both Ubuntu and Darwin

### Steps to reproduce

1. Get the latest nightly binary
2. Start the node

### Expected behaviour

Fast, progressive catchup.

### Actual behaviour

- Ledger will advance a couple hundred blocks
- Ledger will stop advancing for about 18s
- Repeat

This is due to rate limiting, as the logs will report 429 errors, e.g.:

```
HTTPFetcher.getBlockBytes: response status code 429 from '/v1/devnet-v1.0/block/ilk0f'. Response body '' 
```

On the server side this will be reported as "Remote IP Connection Rate Limit".

### PR DESCRIPTION
**Pull request by algorandskiy**
## Summary

While working on rate limiting functionality for libp2p HTTP clients in #5939 the existing WS net functionality was broken and never caught. This PR restores the functionality by making the `RateLimitingTransport` `RateLimitingBoundTransport` - i.e. requiring and enforcing the target peer address (either host:port or peerID). This makes sense since HTTP clients constructed as part of `wsPeerCore` are intended to be used against only this peer. This also means there is no shared `wn.transport` and `RateLimitingBoundTransport` objectare constructed on demand for http clients.

Fixes #6117

## Test Plan

1. Added `RoundTrip` and `GetHTTPClient` unit tests
2. Checked devnet catchup

### CODE REVIEW

File: network/limitcaller/rateLimitingTransport.go [hunk 1]
```diff
@@ -59,37 +59,36 @@ func MakeRateLimitingTransport(phonebook ConnectionTimeStore, queueingTimeout ti
 		ExpectContinueTimeout: defaultTransport.ExpectContinueTimeout,
 		MaxIdleConnsPerHost:   maxIdleConnsPerHost,
 	}
-	return MakeRateLimitingTransportWithRoundTripper(phonebook, queueingTimeout, innerTransport, nil, maxIdleConnsPerHost)
+	return MakeRateLimitingBoundTransportWithRoundTripper(phonebook, queueingTimeout, innerTransport, target)
 }
 
-// MakeRateLimitingTransportWithRoundTripper creates a rate limiting http transport that would limit the requests rate
-// according to the entries in the phonebook.
-func MakeRateLimitingTransportWithRoundTripper(phonebook ConnectionTimeStore, queueingTimeout time.Duration, rt http.RoundTripper, target interface{}, maxIdleConnsPerHost int) RateLimitingTransport {
```
[the remark this answers is not in the document]
Comment (algorandskiy) [reply network/limitcaller/rateLimitingTransport.go:67]: It looks irrelevant for streaming transport used inside p2phttp

File: network/limitcaller/rateLimitingTransport.go [hunk 2]
```diff
@@ -59,37 +59,36 @@ func MakeRateLimitingTransport(phonebook ConnectionTimeStore, queueingTimeout ti
...
 // RoundTrip connects to the address on the named network using the provided context.
 // It waits if needed not to exceed connectionsRateLimitingCount.
-func (r *RateLimitingTransport) RoundTrip(req *http.Request) (res *http.Response, err error) {
+func (r *RateLimitingBoundTransport) RoundTrip(req *http.Request) (res *http.Response, err error) {
 	var waitTime time.Duration
 	var provisionalTime time.Time
-	queueingDeadline := time.Now().Add(r.queueingTimeout)
-	addrOrPeerID := req.Host
-	// p2p/http clients have per-connection transport and address info so use that
-	if len(req.Host) == 0 && req.URL != nil && len(req.URL.Host) == 0 {
```
[the remark this answers is not in the document]
Comment (algorandskiy) [reply network/limitcaller/rateLimitingTransport.go:84]: this code relied on the fact p2p clients were not setting URL.Host (providing only `/path` porting) and ws clients were setting URL.Host in a parent `HTTPPAddressBoundTransport.RoundTrip`

File: network/limitcaller/rateLimitingTransport.go [hunk 3]
```diff
@@ -59,37 +59,36 @@ func MakeRateLimitingTransport(phonebook ConnectionTimeStore, queueingTimeout ti
...
-		addrInfo, ok := r.targetAddr.(*peer.AddrInfo)
-		if !ok {
-			return nil, errors.New("rateLimitingTransport: request without Host/URL and targetAddr is not a peer.AddrInfo")
-		}
-		addrOrPeerID = string(addrInfo.ID)
+	if r.addrOrPeerID == "" {
+		return nil, errors.New("rateLimitingTransport: target not set")
+	}
+	if req.URL != nil && req.URL.Host != "" && req.URL.Host != r.addrOrPeerID {
```
Comment (gmalouf) [inline network/limitcaller/rateLimitingTransport.go:85]: This is basically saying "if there is an http address target, it has to match the request url".

File: network/wsNetwork.go [hunk 4]
```diff
@@ -1975,8 +1972,18 @@ func (wn *WebsocketNetwork) numOutgoingPending() int {
 // GetHTTPClient returns a http.Client with a suitable for the network Transport
 // that would also limit the number of outgoing connections.
 func (wn *WebsocketNetwork) GetHTTPClient(address string) (*http.Client, error) {
+	url, err := addr.ParseHostOrURL(address)
+	if err != nil {
+		return nil, err
+	}
+
+	maxIdleConnsPerHost := int(wn.config.ConnectionsRateLimitingCount)
```
Comment (gmalouf) [inline network/wsNetwork.go:1980]: Why was this moved out of setup?

**Review by gmalouf — COMMENTED** [review]
Asked a few questions, mostly looks good.

File: network/limitcaller/rateLimitingTransport.go (hunk 3 above)
Comment (algorandskiy) [reply network/limitcaller/rateLimitingTransport.go:85]: yes since it is "bound" limiter and transport

File: network/wsNetwork.go (hunk 4 above)
Comment (algorandskiy) [reply network/wsNetwork.go:1980]: because it is now "bound" transport to a specific target (one extra required argument) so it is created per peer, and not reusing a shared generic instance

**Review by gmalouf — APPROVED** [review]
