### PR TITLE
tests: Fix devmode test

### LINKED ISSUE #3267: Fix Slow DevMode Test (TestDevMode)
### Subject of the issue

This test is inexplicably slow and ends up failing periodically. This could be a byproduct of the environment it's running in or a problem that needs to be resolved.

The test is fairly straightforward. It submits 2 transactions and checks that they are confirmed faster than 2x the normal confirmation time.

Here is the failure:
```
=== RUN   TestDevMode
Created new rootkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet3.rootkey
Created new rootkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet2.rootkey
Created new rootkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet1.rootkey
Created new partkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet3.0.3000000.partkey
Created new partkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet2.0.3000000.partkey
Created new partkey: /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Wallet1.0.3000000.partkey
https://github.com/algorandfoundation/specs/tree/bc36005dbd776e6d1eaf0c560619bb183215645c 100000
algod(5283) : No REST API Token found. Generated token: 7d404e1a5dd5e71e2eae2cd5e0eb34cdf892bf5b6045347424cb0f20fa126df3
algod(5283) : No Admin REST API Token found. Generated token: 137d564df72ca487dd8be53977277bda38b71b3c00cfa4774a9f4f39be5a4211
algod(5283) : Logging to:  /opt/cibuild/project/tmp/out/e2e/128713-1638452531109/go/TestDevMode/Node/node.log
algod(5283) : Deadlock detection is set to: enabled (Default state is 'enable')
algod(5283) : Initializing the Algorand node... 
algod(5283) : Success!
algod(5283) : ⇨ http server started on 127.0.0.1:8080
algod(5283) : Node running and accepting RPC requests over HTTP on port 127.0.0.1:8080. Press Ctrl-C to exit
    devmode_test.go:58: 
        	Error Trace:	devmode_test.go:58
        	Error:      	Should be true
        	Test:       	TestDevMode
        	Messages:   	Transactions should be quickly confirmed faster than usual.
algod(5283) : Exiting on terminated
--- FAIL: TestDevMode (19.20s)
```

### PR DESCRIPTION
**Pull request by Eric-Warehime**
## Summary

Re-enables this devmode test.

Closes #3267 (though I've not been able to see the slow/flakiness happen). It's possible that re-enabling this will just cause nightlies to fail periodically, but the nightly run I did has not failed in this way yet.

We should keep an eye on the nightlies and see if this is still causing flakiness.

## Test Plan

Ran nightly tests on this to validate that the test passes on them (since it will be skipped during regular per-PR CI runs).

Here is the resulting run: https://app.circleci.com/pipelines/github/algorand/go-algorand/13978/workflows/ba87d853-cec2-4473-86f4-c7fdd65caa66

The one failure in that is from an unrelated issues relating to running the nightly tests on a fork branch.

### CODE REVIEW

**Review by tzaffi — COMMENTED** [review]
Looks promising, but after around 10 minutes hunting for the log that shows the that `devmode_test.go` ran I couldn't find it. Would you mind providing a link?

**Review by algochoi — COMMENTED** [review]
Looking good - I think the test run is reported on this line: https://app.circleci.com/pipelines/github/algorand/go-algorand/13978/workflows/ba87d853-cec2-4473-86f4-c7fdd65caa66/jobs/227972/parallel-runs/2?filterBy=ALL&invite=true#step-114-453

I can't really tell if this test will be flaky or not based on one run, but it looks okay here (executed within 15.78 seconds, whereas the test will fail after ~19 seconds). 

Also I'm not sure if waiting 8 seconds for 2 transaction confirmations is enough to differentiate dev mode from a normal network (or whether this will be future proof if block times get faster)?

File: test/e2e-go/features/devmode/devmode_test.go [hunk 1]
```diff
@@ -54,14 +53,15 @@ func TestDevMode(t *testing.T) {
 
 	// 2 transactions should be sent within one normal confirmation time.
 	for i := uint64(0); i < 2; i++ {
-		txn = fixture.SendMoneyAndWait(firstRound+i, 100000, 1000, sender.Address, receiver.String(), "")
-		require.Equal(t, firstRound+i, txn.Txn.Txn.FirstValid)
+		txn = fixture.SendMoneyAndWait(firstRound+i, 100001, 1000, sender.Address, receiver.String(), "")
+		// SendMoneyAndWait subtracts 1 from firstValid
+		require.Equal(t, firstRound+i-1, uint64(txn.Txn.Txn.FirstValid))
```
Comment (tzaffi) [inline test/e2e-go/features/devmode/devmode_test.go:58]:
```suggestion
    round := firstRound+i
		txn = fixture.SendMoneyAndWait(round, 100001, 1000, sender.Address, receiver.String(), "")
		// SendMoneyAndWait subtracts 1 from firstValid
		require.Equal(t, round-1, uint64(txn.Txn.Txn.FirstValid))
```
Ignorable nit. Just a bit easier to read.

File: test/e2e-go/features/devmode/devmode_test.go [hunk 2]
```diff
@@ -54,14 +53,15 @@ func TestDevMode(t *testing.T) {
...
 	}
 	require.True(t, time.Since(start) < 8*time.Second, "Transactions should be quickly confirmed faster than usual.")
 
 	// Without transactions there should be no rounds even after a normal confirmation time.
 	time.Sleep(10 * time.Second)
 	status, err := fixture.LibGoalClient.Status()
 	require.NoError(t, err)
-	require.Equal(t, txn.ConfirmedRound, status.LastRound, "There should be no rounds without a transaction.")
+	require.Equal(t, *txn.ConfirmedRound, status.LastRound, "There should be no rounds without a transaction.")
```
Comment (tzaffi) [inline test/e2e-go/features/devmode/devmode_test.go:66]: How did this ever pass? The following simple test fails:

```go
type PointerValue struct {
	Pointer *int
}

func TestPointerValue(t *testing.T) {
	zero := 0
	pv := PointerValue{&zero}
	require.Equal(t, 0, pv.Pointer)
}
```

Comment (tzaffi) [reply test/e2e-go/features/devmode/devmode_test.go:66]: (this is an argument for generics)

**Review by winder — COMMENTED** [review]
Per live discussion: we can avoid the timing issue by using the new round offset feature. This should allow the test to run without sleeping and verify that transactions were created with devmode.

File: test/e2e-go/features/devmode/devmode_test.go (hunk 2 above)
Comment (Eric-Warehime) [reply test/e2e-go/features/devmode/devmode_test.go:80]: I'm not sure how it passed before...I suspect it wasn't returning a pointer at some point?

File: test/e2e-go/features/devmode/devmode_test.go [hunk 3]
```diff
@@ -50,18 +50,32 @@ func TestDevMode(t *testing.T) {
...
+		require.Equal(t, round-1, uint64(txn.Txn.Txn.FirstValid))
+		newBlk, err := fixture.AlgodClient.Block(round)
+		require.NoError(t, err)
+		newBlkSeconds, _ := math.Modf(newBlk.Block["ts"].(float64))
+		require.GreaterOrEqual(t, time.Unix(int64(newBlkSeconds), 0), startTime.Add(1_000_000*time.Second))
 	}
-	require.True(t, time.Since(start) < 8*time.Second, "Transactions should be quickly confirmed faster than usual.")
 
 	// Without transactions there should be no rounds even after a normal confirmation time.
 	time.Sleep(10 * time.Second)
```
Comment (winder) [inline test/e2e-go/features/devmode/devmode_test.go:77]: What do you think about removing the second phase of this test?

File: test/e2e-go/features/devmode/devmode_test.go [hunk 4]
```diff
@@ -50,18 +50,32 @@ func TestDevMode(t *testing.T) {
...
 	for i := uint64(0); i < 2; i++ {
-		txn = fixture.SendMoneyAndWait(firstRound+i, 100000, 1000, sender.Address, receiver.String(), "")
-		require.Equal(t, firstRound+i, txn.Txn.Txn.FirstValid)
+		round := firstRound + i
+		txn = fixture.SendMoneyAndWait(round, 100001, 1000, sender.Address, receiver.String(), "")
+		// SendMoneyAndWait subtracts 1 from firstValid
+		require.Equal(t, round-1, uint64(txn.Txn.Txn.FirstValid))
+		newBlk, err := fixture.AlgodClient.Block(round)
+		require.NoError(t, err)
+		newBlkSeconds, _ := math.Modf(newBlk.Block["ts"].(float64))
```
Comment (tzaffi) [inline test/e2e-go/features/devmode/devmode_test.go:72]: Is there a reason to prefer `math.Modf(...)` over `int(...)` here?

Comment (algochoi) [reply test/e2e-go/features/devmode/devmode_test.go:72]: On my local machine, removing `math.Modf` seems to do the same thing and passes the checks:

```suggestion
		newBlkSeconds, _ := newBlk.Block["ts"].(float64)
```

File: test/e2e-go/features/devmode/devmode_test.go [hunk 5]
```diff
@@ -50,18 +50,32 @@ func TestDevMode(t *testing.T) {
 	txn := fixture.SendMoneyAndWait(0, 100000, 1000, sender.Address, receiver.String(), "")
 	require.NotNil(t, txn.ConfirmedRound)
 	firstRound := *txn.ConfirmedRound + 1
-	start := time.Now()
+	blk, err := fixture.AlgodClient.Block(*txn.ConfirmedRound)
+	require.NoError(t, err)
+	seconds, _ := math.Modf(blk.Block["ts"].(float64))
+	startTime := time.Unix(int64(seconds), 0)
+	blkOffset := uint64(1_000_000)
```
Comment (algochoi) [inline test/e2e-go/features/devmode/devmode_test.go:57]: tiny nit: maybe set this as a constant (unfortunately still need to convert uint64 to a time.duration below though) and add a comment on testing consecutive timestamps in dev mode

File: test/e2e-go/features/devmode/devmode_test.go [hunk 6]
```diff
@@ -50,18 +50,32 @@ func TestDevMode(t *testing.T) {
...
-		txn = fixture.SendMoneyAndWait(firstRound+i, 100000, 1000, sender.Address, receiver.String(), "")
-		require.Equal(t, firstRound+i, txn.Txn.Txn.FirstValid)
+		round := firstRound + i
+		txn = fixture.SendMoneyAndWait(round, 100001, 1000, sender.Address, receiver.String(), "")
+		// SendMoneyAndWait subtracts 1 from firstValid
+		require.Equal(t, round-1, uint64(txn.Txn.Txn.FirstValid))
+		newBlk, err := fixture.AlgodClient.Block(round)
+		require.NoError(t, err)
+		newBlkSeconds, _ := math.Modf(newBlk.Block["ts"].(float64))
+		require.GreaterOrEqual(t, time.Unix(int64(newBlkSeconds), 0), startTime.Add(1_000_000*time.Second))
```
[the remark this answers is not in the document]
Comment (Eric-Warehime) [reply test/e2e-go/features/devmode/devmode_test.go:73]: I think we need to keep it greater than or equal because the offset is just added to the clock time. So two separate txns `1` second apart could have block times `1_000_001` seconds apart if the offset is `1_000_000`.

File: test/e2e-go/features/devmode/devmode_test.go (hunk 3 above)
Comment (Eric-Warehime) [reply test/e2e-go/features/devmode/devmode_test.go:77]: Seems fine to me.

File: test/e2e-go/features/devmode/devmode_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (winder) [reply test/e2e-go/features/devmode/devmode_test.go]: It should be added to the previous block time, so I'm pretty sure this is deterministic.

@algochoi correct me if I'm wrong.

[the remark this answers is not in the document]
Comment (algochoi) [reply test/e2e-go/features/devmode/devmode_test.go]: That's true @winder . The current test needs to be modified so that the initial `seconds` or `startTime` is updated inside the loop. The second iteration will make the delta 2 million seconds so the equal will fail the second time.

[the remark this answers is not in the document]
Comment (Eric-Warehime) [reply test/e2e-go/features/devmode/devmode_test.go]: Done.

**Review by algochoi — APPROVED** [review]
thanks!!
