### PR TITLE
simulate: fix signers

### LINKED ISSUE #5914: simulate fails with empty signature on a rekeyed account
### Subject of the issue

When using simulate with the "allow empty signatures" option, algod will still check the authorizer causing a failure 

### Your environment

3.21.0.stable [rel/stable] (commit #2c328251)

### Steps to reproduce

1. Attempt to simulate a transaction from an account with a non-zero `auth-addr` and no signature

### Expected behaviour

algod simulates the transaction without a failure

### Actual behaviour

faliure message: `transaction UOT36H44LYQHOPMLVMVOOBO6EEMRZABHC34XMWPKSY3PGFZWMYOQ: should have been authorized by 3REKUY27LL7OXNA4A63DYMUV766WTRUK5LKSDKAYC2JI7O2GKZR73MK5LA but was actually authorized by P7WXTXBYUVF4AMP6ERLZS6A3JZRMCWCJNJ35ADW5QRZS3F4BL3ZASW47WI`

### Test Script

```import algosdk, { AtomicTransactionComposer } from 'algosdk'
import * as algokit from '@algorandfoundation/algokit-utils'

async function main() {
    const algod = new algosdk.Algodv2('a'.repeat(64), 'http://localhost', 4001)
    const kmd = new algosdk.Kmd('a'.repeat(64), 'http://localhost', 4002)

    const sender = algosdk.generateAccount()
    const authAddr = algosdk.generateAccount()

    await algokit.ensureFunded({ accountToFund: sender.addr, minSpendingBalance: algokit.microAlgos(2_000) }, algod, kmd)

    console.log(`Sender: ${sender.addr}, Auth: ${authAddr.addr}`)

    const rekeyTxn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        from: sender.addr,
        to: sender.addr,
        amount: 0,
        rekeyTo: authAddr.addr,
        suggestedParams: await algod.getTransactionParams().do()
    })

    const firstEmpySimAtc = new AtomicTransactionComposer()

    const simReq = new algosdk.modelsv2.SimulateRequest({
        txnGroups: [],
        allowUnnamedResources: true,
        allowEmptySignatures: true,
    })

    firstEmpySimAtc.addTransaction({ txn: rekeyTxn, signer: algosdk.makeEmptyTransactionSigner() })

    const preSimAuthAddr = (await algod.accountInformation(sender.addr).do())['auth-addr']
    console.log(`Pre simulate auth addr: ${preSimAuthAddr}`)
    const firstResp = await firstEmpySimAtc.simulate(algod, simReq)

    console.log('failureMessage:', firstResp.simulateResponse.txnGroups[0].failureMessage)

    console.log('Empty signer simulate worked')

    const rekeyAtc = new AtomicTransactionComposer()
    rekeyAtc.addTransaction({ txn: rekeyTxn, signer: algosdk.makeBasicAccountTransactionSigner(sender) })

    const preExecuteAuthAddr = (await algod.accountInformation(sender.addr).do())['auth-addr']
    console.log(`Pre execute auth addr: ${preExecuteAuthAddr}`)
    await rekeyAtc.execute(algod, 3)

    console.log(`${sender.addr} now rekeyed to ${(await algod.accountInformation(sender.addr).do())['auth-addr']}`)

    const secondEmpySimAtc = new AtomicTransactionComposer()

    const rekeyBackTxn = algosdk.makePaymentTxnWithSuggestedParamsFromObject({
        from: sender.addr,
        to: sender.addr,
        amount: 0,
        rekeyTo: sender.addr,
        suggestedParams: await algod.getTransactionParams().do()
    })

    secondEmpySimAtc.addTransaction({ txn: rekeyBackTxn, signer: algosdk.makeEmptyTransactionSigner() })

    const group = await secondEmpySimAtc.gatherSignatures()

    group.forEach((txn) => {
        console.log(algosdk.decodeSignedTransaction(txn).sig)
    })

    const resp = await secondEmpySimAtc.simulate(algod, simReq)

    // failureMessage: transaction UOT36H44LYQHOPMLVMVOOBO6EEMRZABHC34XMWPKSY3PGFZWMYOQ: should have been authorized by 3REKUY27LL7OXNA4A63DYMUV766WTRUK5LKSDKAYC2JI7O2GKZR73MK5LA but was actually authorized by P7WXTXBYUVF4AMP6ERLZS6A3JZRMCWCJNJ35ADW5QRZS3F4BL3ZASW47WI
    console.log('failureMessage:', resp.simulateResponse.txnGroups[0].failureMessage)
}

main()
```

### PR DESCRIPTION
**Pull request by joe-p**
## Summary

This is a new feature in simulate that will close #5914. Auth address correction is done is two places:

1. In `simulateWithTracer` the txn fields will be analyzed and auth addrs for txns will be updated past on previous `rekeyTo` fields
2. In `AfterProgram` the auth addr field for all txns up to the next app call will be corrected

This allows one to simulate with empty signatures without knowing the proper auth addresses when forming the group.

## Test Plan

Simple test to ensure the endpoint works as expected in `test/e2e-go/restAPI/simulate/simulateRestAPI_test.go` and more comprehensive testing in `ledger/simulation/simulation_eval_test.go`

### CODE REVIEW

**Comment by joe-p** [comment]
@jasonpaulos let me know what you think about this general approach. If it looks good, I can work on the endpoint and more tests

File: ledger/simulation/simulator.go [hunk 1]
```diff
@@ -205,14 +204,41 @@ func (s Simulator) evaluate(hdr bookkeeping.BlockHeader, stxns []transactions.Si
...
+	if fixAuthAddr {
+		// Map of rekeys for senders in the group
+		staticRekeys := make(map[basics.Address]basics.Address)
+
+		for i := range txgroup {
+			sender := txgroup[i].SignedTxn.Txn.Sender
+
+			if authAddr, ok := staticRekeys[sender]; ok {
+				// If there is a static rekey for the sender set the auth addr to that address
+				txgroup[i].SignedTxn.AuthAddr = authAddr
```
Comment (jasonpaulos) [inline ledger/simulation/simulator.go:225]: We may want to only modify txn AuthAddrs if the transaction has a missing signature. Otherwise the signature is a bit pointless. Worth thinking about at leaset

**Review by jasonpaulos — COMMENTED** [review]
The direction makes sense to me. This will need extensive testing.

What are you thinking about for how to enable this? At the moment my preference would be a boolean alongside `AllowEmptySignatures`, which you'd only be allowed to set if `AllowEmptySignatures` is also set

**Comment by joe-p** [comment]
Also I'm switching from the terminology "fix auth addr" to "fix signer" to avoid confusion between the auth addr for a given account in the ledger and the signer for the transaction, making it clear the ledger remains unchanged and its just txns that are getting modified.

**Comment by joe-p** [comment]
> The only problem is that the response structure may make it difficult to associate this additional information with inner transactions.

Unless you are thinking of functionality that iI am not, we're only modifying the signers on the outer transactions, so we only need to add additional information to the outers.

**Comment by jasonpaulos** [comment]
> Unless you are thinking of functionality that I am not, we're only modifying the signers on the outer transactions, so we only need to add additional information to the outers.

Good point, this plan should have no problems then

File: test/e2e-go/restAPI/simulate/simulateRestAPI_test.go [hunk 2]
```diff
@@ -2695,3 +2695,86 @@ int 1
...
+	txn.Group = gid
+
+	simulateRequest := v2.PreEncodedSimulateRequest{
+		TxnGroups: []v2.PreEncodedSimulateRequestTransactionGroup{
+			{
+				Txns: []transactions.SignedTxn{{Txn: rekeyTxn}, {Txn: txn}},
+			},
+		},
+		AllowEmptySignatures: true,
+		FixSigners:           true, // When this is true: HTTP 400 Bad Request: failed to decode object: json decode error [pos 1]: only encoded map or array can be decoded into a struct
```
Comment (joe-p) [inline test/e2e-go/restAPI/simulate/simulateRestAPI_test.go:2746]: @jasonpaulos Any idea why this is throwing a JSON decode error? I've updated `PreEncodedSimulateRequest` with the proper codec tag, but the request still seems to be malformed for some reason.

Comment (jasonpaulos) [reply test/e2e-go/restAPI/simulate/simulateRestAPI_test.go:2746]: I'm not sure what decode error you're seeing. When I run this locally, I only see that the transaction failed with the wrong auth addr.

Although I did have to merge in master to get the code to compile, since we updated to go 1.21. I suggested doing the same, making sure you're on go 1.21 as well, and see if that helps.

I've opened this with my merge commit in case it's helpful: https://github.com/joe-p/go-algorand/pull/1

Comment (joe-p) [reply test/e2e-go/restAPI/simulate/simulateRestAPI_test.go]: Ah ok I wasn't rebuilding algod, thinking the test runner was doing it automatically, thus the encoding error. 

> When I run this locally, I only see that the transaction failed with the wrong auth addr.

I missed the `convert...` functions in the simulate handler. [e8cec95](https://github.com/algorand/go-algorand/pull/5942/commits/e8cec9520bedf6ca62012ebafaad63efe1f994de) fixed that and the request is properly working now. The response is still missing the `FixedSigner` in the `TxnResult` for some reason, but at least the request is working now.

**Comment by joe-p** [comment]
@jasonpaulos I need to modify the test case to make sure the change I made in 89c20b5 works as expected with nested app calls, but other than that it's ready for review.

**Review by jasonpaulos — COMMENTED** [review]
Mostly looks good, but I left a few asks and I made this sub-PR with mostly test changes: https://github.com/joe-p/go-algorand/pull/3

File: ledger/simulation/simulator.go [hunk 3]
```diff
@@ -304,5 +350,23 @@ func (s Simulator) Simulate(simulateRequest Request) (Result, error) {
 	}
 	simulatorTracer.result.TxnGroups[0].AppBudgetConsumed = totalCost
 
+	// Set the FixedSigner for each transaction that had a signer change during evaluation
+	for i := range simulatorTracer.result.TxnGroups[0].Txns {
+		givenSigner := simulatorTracer.result.TxnGroups[0].Txns[i].Txn.AuthAddr
+		tracerSigner := simulatorTracer.groups[0][i].SignedTxn.AuthAddr
+
+		tracerSignerIsSender := tracerSigner == simulatorTracer.groups[0][i].SignedTxn.Txn.Sender
```
[the remark this answers is not in the document]
Comment (jasonpaulos) [reply ledger/simulation/simulator.go:358]: I ended up doing this in https://github.com/joe-p/go-algorand/pull/3

File: ledger/simulation/tracer.go [hunk 4]
```diff
@@ -512,4 +514,43 @@ func (tracer *evalTracer) AfterProgram(cx *logic.EvalContext, pass bool, evalErr
...
+				if err != nil {
+					panic(err)
+				}
+
+				knownAuthAddrs[sender] = data.AuthAddr
+
+				if blankSig {
+					stxn.AuthAddr = data.AuthAddr
+				}
+			}
```
[the remark this answers is not in the document]
Comment (joe-p) [reply ledger/simulation/tracer.go]: Yeah good call. Done in [65cbc51](https://github.com/algorand/go-algorand/pull/5942/commits/65cbc51c657db8fea3a20bfc9bf0ac2f67ff44b8)

**Review by jasonpaulos — APPROVED** [review]

File: ledger/simulation/simulator.go [hunk 5]
```diff
@@ -208,14 +208,56 @@ func (s Simulator) evaluate(hdr bookkeeping.BlockHeader, stxns []transactions.Si
...
+				if err != nil {
+					return nil, err
+				}
+
+				if txnHasNoSignature(*stxn) {
+					stxn.AuthAddr = data.AuthAddr
+					if stxn.AuthAddr == sender {
+						stxn.AuthAddr = basics.Address{}
+					}
+				}
```
Comment (algorandskiy) [inline ledger/simulation/simulator.go:246]:
```suggestion
				if txnHasNoSignature(*stxn) {
					var data ledgercore.AccountData
					data, _, _, err = s.ledger.LookupAccount(s.ledger.start, sender)
					if err != nil {
						return nil, err
					}

					stxn.AuthAddr = data.AuthAddr
					if stxn.AuthAddr == sender {
						stxn.AuthAddr = basics.Address{}
					}
				}
```

**Review by algorandskiy — COMMENTED** [review]
LGTM one small suggestion

**Comment by joe-p** [comment]
Thanks @algorandskiy. Apologies for the force push. Fixed a typo in the commit message and didn't realize it would dismiss @jasonpaulos review status

**Review by jasonpaulos — APPROVED** [review]

**Review by algorandskiy — APPROVED** [review]
