### PR TITLE
Separate the error message for duplicate txn id and lease

### LINKED ISSUE #1637: [Investigate] Confusing error message "transaction already in ledger" when leases are used
### Subject of the issue

When a transaction is rejected because of the lease, the error message is: "transaction already in ledger" which may be confusing, as the actual transaction is not in the ledger.

### Your environment
* Software version: `algod -v`
```
8590000134
2.1.6.stable [rel/stable] (commit #df65da2b)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```
* Node status if applicable: `goal node status`
```
Last committed block: 9999365
Time since last block: 2.1s
Sync Time: 0.0s
Last consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
Next consensus protocol: https://github.com/algorandfoundation/specs/tree/3a83c4c743f8b17adfd73944b4319c25722a6782
Round for next consensus protocol: 9999366
Next consensus protocol supported: true
Last Catchpoint: 
Genesis ID: testnet-v1.0
Genesis hash: SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=
```
* Operating System details. Ubuntu 18.04.5 LTS in a VM
* In many cases log files and cadaver files are also useful to include. Since these files may be large, an Algorand developer may request them later. These files may include public addresses that you're participating with. If that is a concern please be sure to scrub that data.

### Steps to reproduce

```bash
$ goal account new
Created new account with address PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE

$ goal clerk send --amount 1234 --from PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE --to PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE --lease "PV1JxiWg+aj+gCjybRUJ0mjCQdKMWbK7uOu0p1lWETQ="
Sent 1234 MicroAlgos from account PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE to address PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE, transaction ID: KNSDXKM3V5KSGQQNVP35JHM4JN3W4IJTKIIGHXOHMHKNRFBG6UCA. Fee set to 1000
Transaction KNSDXKM3V5KSGQQNVP35JHM4JN3W4IJTKIIGHXOHMHKNRFBG6UCA still pending as of round 9999260
Transaction KNSDXKM3V5KSGQQNVP35JHM4JN3W4IJTKIIGHXOHMHKNRFBG6UCA committed in round 9999262

$ goal clerk send --amount 1234 --from PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE --to PRCRM4AIUD5TWUWUYLMCNL6J5LQZJ54AQOKEJTVOW2K2NXCXVGIJD5Q6IE --lease "PV1JxiWg+aj+gCjybRUJ0mjCQdKMWbK7uOu0p1lWETQ="
Couldn't broadcast tx with algod: HTTP 400 Bad Request: TransactionPool.Remember: transaction already in ledger: 2ERID7VTY2BYEXJIADWNFJ2VBKOR52HHFN2TNJMDAXM76W7AYBRA
```

### Expected behaviour

The error message explains that the issue is with the lease.

### Actual behaviour

The error message says that the transaction already is in the ledger, which is it not.

## Urgency/relative priority
Definitely a valid argument that we should give better error messages, but it's also probably not the most urgent task. Will definitely keep in the backlog though.

### PR DESCRIPTION
**Pull request by tsachiherman**
## Summary

Convert isDup to checkDup and move error object generation into checkDup so that we can differentiate between txid duplicate and txlease collision.

## Test Plan

Update existing unit tests and add new one.

resolves #1637

### CODE REVIEW

**Review by nicholasguoalgorand — APPROVED** [review]
LGTM

File: ledger/error.go [hunk 1]
```diff
@@ -33,6 +33,19 @@ func (tile TransactionInLedgerError) Error() string {
...
 }
 
+// LeaseInLedgerError is returned when a transaction cannot be added because it has a lease that already being used in the relavant rounds
+type LeaseInLedgerError struct {
+	txid  transactions.Txid
+	lease txlease
+}
+
+// Error implements the error interface for the LeaseInLedgerError stuct
+func (lile LeaseInLedgerError) Error() string {
```
Comment (algorandskiy) [inline ledger/error.go:43]: `lile LeaseInLedgerError` to reduce copying?

**Review by algorandskiy — DISMISSED** [review]

File: ledger/error.go (hunk 1 above)
Comment (tsachiherman) [reply ledger/error.go:43]: not sure what you mean by saying that. Are you asking if I can convert that to a `func (lile *LeaseInLedgerError) Error() string` so that the data members would not need to be copied ?

Comment (algorandskiy) [reply ledger/error.go:43]: sorry, yes

**Review by algorandskiy — APPROVED** [review]
