### PR TITLE
API: MaxTealSourceBytes to 512 kb

### LINKED ISSUE #6031: request body too large
### Subject of the issue

I hit error: "request body too large" when deploying contract

Note that in my case this error has occured after upgrading the tealscript version and algokit which added more comments to the generated client code.

Please increase post body size to the limit where any future build of the contract would rather fail on "teal code too big" instead of the input body is too big.

Also note that Joe fixed the same thing for compiling contract between version of 0.95.0 and 0.95.1 and just removed the comments. But i think the increase of allowed post body in the algod is better solution then to trim comments.

### Your environment

```
algokit localnet status
# algod status
Status: Running
Port: 4001
Last round: 558
Time since last round: 170.8s
Genesis ID: dockernet-v1
Genesis hash: LThUC5TvTwIUgf7bTZNMSZkVdd2iDzCTx4RYNyYQe/M=
Version: 3.24.0
# conduit status
Status: Running
# indexer-db status
Status: Running
# indexer status
Status: Running
Port: 8980
Last round: 558
Version: 3.5.0
```

### Steps to reproduce

1. git clone https://github.com/scholtz/BiatecCLAMM
2. cd BiatecCLAMM
3. git checkout feat/update-tealscript
4. algokit localnet start
5. npm i
6. npm run test

### Expected behaviour

If contract is too large i expect to receive contract too large error message.

### Actual behaviour

image

```
URLTokenBaseHTTPError: Network request error. Received status 400 (Bad Request): http: request body too large
        {
      response: {
        body: { message: 'http: request body too large' },
        status: 400,
        headers: {
          '43': 'content-length',
          'application/json; charset=UTF-8': 'content-type',
          'Sat, 15 Jun 2024 09:55:00 GMT': 'date',
          Origin: 'vary'
        },
        text: '{"message":"http: request body too large"}\n',
        ok: false
      },
      status: 400
    }
```

### PR DESCRIPTION
**Pull request by scholtz**
MaxTealSourceBytes to 1M 

## Summary

Fixes #6031

## Test Plan

Test plan not needed. Just increases one constant to little bigger number so that the teal compilation proceed.

### CODE REVIEW

**Comment by jannotti** [comment]
The issue you link to says:

>Please increase post body size to the limit where any future build of the contract would rather fail on "teal code too big" instead of the input body is too big.

I don't see any place in go-algorand that such an error ("teal code too big") is returned. Can you point it out? Ideally, there should indeed be a test that shows that such an error is generated.

**Comment by scholtz** [comment]
@jannotti Just read the https://github.com/algorand/go-algorand/issues/6031 thread pls. You can reproduce the issue when you create teal code longer then 200kb .. Feel free to write test for it.

You can reproduce the issue when you clone https://github.com/scholtz/BiatecCLAMM/tree/feat/update-tealscript and run `npm i` and `npm run test`

**Comment by jannotti** [comment]
> @jannotti Just read the #6031 thread pls. You can reproduce the issue when you create teal code longer then 200kb .. Feel free to write test for it.
> 
> You can reproduce the issue when you clone https://github.com/scholtz/BiatecCLAMM/tree/feat/update-tealscript and run `npm i` and `npm run test`

Since I quoted from that thread in my message, and I was the first commenter on that thread, you may safely assume that I have read it and understand it.  Nowhere does that thread explain where the error "teal code to big" might come from, since that text does not appear in go-algorand.

I suspect that the error message in question is somewhere in algokit, which would also explain why you are so reluctant to provide a test case. It is impossible to provide a test case in go-algorand because you are describing a poor interaction between algokit and go-algorand, not a bug in go-algorand.  It appears that algokit does not understand that when it receives a "request body too large" response, it should report the error to the user as "teal code to big".  That is something that should be changed in algokit.

I do not object to raising the size of programs that algod can assemble, but if the fundamental problem is that algokit does not understand the error in question, we have simply masked the problem until a larger a program is sent. If algokit has a built-in constant that limits the size of teal code to 1M, that chould also be changed in algokit. It would be better for algokit to simply submit what it's given, understand the error "request body too large" and report the size limitation when the error is received.

At any rate, there's work to be done in algokit, and possible _also_ a raise of this constant if we actually think it's reasonable to send such large programs to algod. As is, this change masks the real problem.

File: daemon/algod/api/server/v2/handlers.go [hunk 1]
```diff
@@ -64,8 +64,8 @@ import (
 // MaxTealSourceBytes sets a size limit for TEAL source programs for requests
 // Max TEAL program size is currently 8k
 // but we allow for comments, spacing, and repeated consts
-// in the source TEAL, so we allow up to 200KB
-const MaxTealSourceBytes = 200_000
+// in the source TEAL, so we allow up to 1MB
+const MaxTealSourceBytes = 1_000_000
```
Comment (jannotti) [inline daemon/algod/api/server/v2/handlers.go:68]: If the previous hand-wavy argument that 200_000 was reasonable has caused problems, then there should be a number that is _correct_ in the sense that it can't cause those problems. But I don't see what those problems were, exactly, nor why 1MB is the number that is correct to solve them.

**Comment by scholtz** [comment]
hi @jannotti I believe the error is thrown here in algod: https://github.com/algorand/go-algorand/blob/48a539f3307ea970c7a1fd67266c15108a5fdebc/daemon/algod/api/server/v2/test/handlers_test.go#L1560 when building the contract with bigger size then allowed.. Feel free to rename the text "http: request body too large" to "We allow maximum 1MB of teal code to be compiled" .. but my issue is not to get proper error text, but not to get the error when compiling.. i believe 1MB should be sustainable and usable long term for any optional extensions.. it does not effect any of other compilation limitations at the moment like opcode budget checking...

I believe this teal code size limit is not something that should limit devs from building, but rather the opcode budget should be proper limit.

Please merge it in pls.

File: daemon/algod/api/server/v2/handlers.go (hunk 1 above)
Comment (scholtz) [reply daemon/algod/api/server/v2/handlers.go:68]: my current teal code for clamm when i remove the comments from the code is 190kb .. when i keep the comments its 210kb.. i prefer not to code a feature to trim the comments from the higher level language because i like when the code is commented, and it is better for auditing process when teal code is commented

i believe 1MB is the better limit because this way devs will hit different limits and not the length of teal code program limit

Comment (jannotti) [reply daemon/algod/api/server/v2/handlers.go:68]: Could you tell me how many bytes your teal compiles to?  Since we are considering raising the potential size of a logicsig to 16kb, I'd like to have enough headroom to allow for program that compiles to something that big, along with a reasonable amount of comments.

**Comment by pbennett** [comment]
What's the compiled result though?  I've got a contract that compiles to around 7k (when the maximum contract allowed is 8k !!) and the teal (w/ source lines in commetns, etc.) is only 142K.

There's no way your contract will be runnable not without raising the approval program size massively - which is a different request.

**Comment by joe-p** [comment]
I imagine a significant factor here is `bytes` pseudo-op arguments. For example, TEALScript uses `bytes 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF` for uint256 encoding. During assembly all of these values get reduce due to it being put in the constant block, but that doesn't help if the bottleneck is sending the TEAL to the node. For this specific scenario a solution is to optimize byte constants prior to sending to algod.

**Comment by algorandskiy** [comment]
I guess it is safe to raise since it is developer API (normally restricted)

**Comment by jannotti** [comment]
Can I get this answer?  I'm totally ok with using a constant that is reasonably proportional to how many bytes you need to end up with a program that's about as big as allowed:

> Could you tell me how many bytes your teal compiles to? Since we are considering raising the potential size of a logicsig to 16kb, I'd like to have enough headroom to allow for program that compiles to something that big, along with a reasonable amount of comments.

**Comment by jannotti** [comment]
> I've got a contract that compiles to 6320 bytes or so (and will grow) and the teal for it is 142K.

If we assume this is a reasonable ratio of source TEAL bytes to bytecode (22.4) then a maximum sized (current) app of 8k would need 8096*22.4 = 182kb source program.  Since we're contemplating 16000 byte logicsigs, we might want to compile programs about 16000*22.4 = 358kb.

Allow a little slack, and I'd be in favor of a half mb limit.

I won't fight that hard against 1 mb if others prefer it.  Please speak up.

File: daemon/algod/api/server/v2/handlers.go (hunk 1 above)
Comment (jannotti) [inline daemon/algod/api/server/v2/handlers.go:68]:
```suggestion
// in the source TEAL. We have some indication that real TEAL programs with comments are about 20 times bigger than the bytecode they produce, and we may soon allow 16,000 byte logicsigs, implying a maximum of 320kb. Let's call it half a meg for a little room to spare.
const MaxTealSourceBytes = 512*1024
```

**Review by jannotti — APPROVED** [review]
With my suggested change, I'm happy. With the 1MB limit, I'm basically ok too.  I'll approve and let another approver weigh in.

File: daemon/algod/api/server/v2/handlers.go (hunk 1 above)
Comment (gmalouf) [reply daemon/algod/api/server/v2/handlers.go:68]: I'd like to see the above change committed, then happy to approve.

**Comment by scholtz** [comment]
i am ok with 512*1024 as well.. thanks for review

**Comment by scholtz** [comment]
@jannotti @gmalouf @algorandskiy Can you merge it please? We are talking about one line of code for 3 months now.

**Review by jannotti — APPROVED** [review]

**Review by gmalouf — APPROVED** [review]

**Comment by gmalouf** [comment]
Please note that all nodes will not support this until the next consensus upgrade goes into effect.
