### PR TITLE
Fix partition recovery tests

### LINKED ISSUE #2384: Broken test: TestBasicPartitionRecovery
## Description
Travis Test Errors Reference Spreadsheet for details on cases where this test has failed: https://docs.google.com/spreadsheets/d/1apjaNvZodnTSIdZaQlpMaqf0nzbKgSYdIWHqvmINHS8/edit#gid=0

### Example Failure
Time: Thu 7/15/2021
Build: https://app.travis-ci.com/github/algorand/go-algorand/jobs/524585138#L1949
Travis Test: Ubuntu AMD64 Integration Test
Package: test/e2e-go/features/partitionRecovery
Test: TestBasicPartitionRecovery  

```
==================
WARNING: DATA RACE
Read at 0x00c00013beba by goroutine 75:
  testing.tRunner.func1()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:960 +0xdd
  runtime.call32()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/asm_amd64.s:539 +0x3a
  testing.(*T).FailNow()
      <autogenerated>:1 +0x43
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*synchTest).FailNow()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/fixture.go:115 +0x97
  github.com/stretchr/testify/require.NoError()
      /home/travis/gopath/pkg/mod/github.com/stretchr/testify@v1.6.1/require/require.go:1038 +0x102
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*RestClientFixture).ClientWaitForRoundWithTimeout()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/restClientFixture.go:114 +0x23a
  github.com/[secure]/go-[secure]/test/e2e-go/features/partitionRecovery.TestPartitionHalfOffline()
      /home/travis/build/[secure]/go-[secure]/test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:233 +0x4f9
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1039 +0x1eb
Previous write at 0x00c00013beba by goroutine 122:
  testing.(*common).FailNow()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:697 +0x4c
  testing.(*T).FailNow()
      <autogenerated>:1 +0x43
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*synchTest).FailNow()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/fixture.go:115 +0x97
  github.com/stretchr/testify/require.NoError()
      /home/travis/gopath/pkg/mod/github.com/stretchr/testify@v1.6.1/require/require.go:1038 +0x102
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*LibGoalFixture).nodeExitWithError()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/libgoalFixture.go:125 +0x2ef
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*LibGoalFixture).nodeExitWithError-fm()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/libgoalFixture.go:107 +0x5f
  github.com/[secure]/go-[secure]/nodecontrol.(*NodeController).StartAlgod.func2()
      /home/travis/build/[secure]/go-[secure]/nodecontrol/algodControl.go:232 +0xe8
Goroutine 75 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1090 +0x700
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1334 +0xa6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1039 +0x1eb
  testing.runTests()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1332 +0x527
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1249 +0x43f
  main.main()
      _testmain.go:52 +0x223
Goroutine 122 (finished) created at:
  github.com/[secure]/go-[secure]/nodecontrol.(*NodeController).StartAlgod()
      /home/travis/build/[secure]/go-[secure]/nodecontrol/algodControl.go:224 +0x5e9
  github.com/[secure]/go-[secure]/netdeploy.Network.startNodes()
      /home/travis/build/[secure]/go-[secure]/netdeploy/network.go:339 +0x333
  github.com/[secure]/go-[secure]/netdeploy.Network.Start()
      /home/travis/build/[secure]/go-[secure]/netdeploy/network.go:293 +0x4f2
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*LibGoalFixture).Start()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/libgoalFixture.go:264 +0xf8
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*LibGoalFixture).setup()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/libgoalFixture.go:101 +0x509
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*LibGoalFixture).Setup()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/libgoalFixture.go:67 +0x91
  github.com/[secure]/go-[secure]/test/framework/fixtures.(*RestClientFixture).Setup()
      /home/travis/build/[secure]/go-[secure]/test/framework/fixtures/restClientFixture.go:43 +0x89
  github.com/[secure]/go-[secure]/test/e2e-go/features/partitionRecovery.TestPartitionHalfOffline()
      /home/travis/build/[secure]/go-[secure]/test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:223 +0x24e
  testing.tRunner()
      /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/testing/testing.go:1039 +0x1eb
==================
=== FAIL: test/e2e-go/features/partitionRecovery TestBasicPartitionRecovery (unknown) 
=== FAIL: test/e2e-go/features/partitionRecovery TestPartitionRecoverySwapStartup (unknown)
```
Doesn't seem to have anything after it specifically so I inclueded the warning that happened before it.

### PR DESCRIPTION
**Pull request by algonautshant**
## Summary
The expected round number is captured before the node stops. However,
it is likely that the node advances to the next round before it is
stopped. When this happens, the test will fail.

This change gets the most up-to-date round number after the node is
stopped, but before inducePartitionTime timeout is waited.

inducePartitionTime is the wait to make sure the expected behavior is
obtained. The round number is captured before this wait.

However, I could not identify in this PR why `TestBasicPartitionRecovery` has failed. Could not find anything in the test, and the failure logs have nothing. 
I suspect that the failure in the other tests triggered the failure, and fixed the other tests, but cannot be sure. 

As for the data race, it is fixed in #2844.

Fixes #2384 and #2545 

## Test Plan
This is a fix for a test.

### CODE REVIEW

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go [hunk 1]
```diff
@@ -135,6 +135,10 @@ func runTestWithStaggeredStopStart(t *testing.T, fixture *fixtures.RestClientFix
 	// Stop Node1
 	nc1.FullStop()
 
+	status, err := fixture.LibGoalClient.Status()
+	a.NoError(err)
+	roundAfterStop := status.LastRound
```
Comment (winder) [inline test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:140]: I haven't used this fixture, could you clarify what happens here? I see node 1 is running at this point and we wait until some rounds have been generated, then stop node 1.

goal is called to figure out which round we were at, but how does goal work when the node is stopped?

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go [hunk 2]
```diff
@@ -152,10 +156,10 @@ func runTestWithStaggeredStopStart(t *testing.T, fixture *fixtures.RestClientFix
 	a.NoError(err)
 
 	// Now wait for us to make progress again.
-	status, err := fixture.LibGoalClient.Status()
+	status, err = fixture.LibGoalClient.Status()
 	a.NoError(err)
 
-	a.Equal(waitForRound, status.LastRound, "We should not have made progress since stopping the first node")
```
Comment (winder) [inline test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: Was the bug that sometimes we would get to `waitForRound+1`, so `waitForRound` did not equal `status.LastRound`?

It seems like there is still a race condition between resuming node 1 and shutting down node 2.

Could we move `fixture.StartNode(nc1.GetDataDir())` to after `nc2.FullStop()` and before `time.Sleep(20 * time.Second)`?

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go [hunk 3]
```diff
@@ -205,10 +213,10 @@ func TestBasicPartitionRecoveryPartOffline(t *testing.T) {
...
+	a.Equal(roundAfterStop, status.LastRound, "We should not have made progress since stopping the first node")
```
Comment (winder) [inline test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:219]: This one looks good.

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go (hunk 2 above)
Comment (winder) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: Maybe that race condition is the point of the test? Not sure exactly what is intended by the name `runTestWithStaggeredStopStart`, the comments in the other 2 tests you changed make the test a bit easier to review. Maybe you could add a similar comment to this test?

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go [hunk 4]
```diff
@@ -253,12 +261,16 @@ func TestPartitionHalfOffline(t *testing.T) {
...
+	roundAfterStop := status.LastRound
+
 	time.Sleep(inducePartitionTime)
 
 	// Get main client to monitor
-	status, err := client.Status()
+	status, err = client.Status()
 	a.NoError(err)
-	a.Equal(waitForRound, status.LastRound, "We should not have made progress since stopping the nodes")
+	a.Equal(roundAfterStop, status.LastRound, "We should not have made progress since stopping the nodes")
```
Comment (winder) [inline test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:273]: Looks good. Same issue here then? We were getting to `waitForRound+1`?

**Review by winder — COMMENTED** [review]
Looks good, just one question about a possible minor improvement to one of the tests.

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go (hunk 1 above)
Comment (algonautshant) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:140]: It picks up the "Primary" node from the network, which is not stopped.

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go (hunk 2 above)
Comment (algonautshant) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: The intend of the test is to make sure that after stopping `Node1`, the network does not make any progress.

If the test proceeds in a timely manner, the node will be before round 3 when `ClientWaitForRoundWithTimeout` is called, and will be at round 3 when Node1 is stopped. 
If this happens, there is no problem. 

However, if the test thread is slow, and by the time `Node1` is stopped, nothing prevents `Node1` from getting all the way to round e.g. 5. This may happen before `ClientWaitForRoundWithTimeout`, or after `ClientWaitForRoundWithTimeout` and before `FullStop`. This can be tested by adding in any of these position sleep of 5 seconds. 

By reading the round number after `FullStop`, we get the round number the network was after `Node1` stopped. It might be a little after it stopped, but it is okay. As long as we make sure the network is not making any progress during the `inducePartitionTime` sleep.

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go (hunk 4 above)
Comment (algonautshant) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:273]: See my explanation above. If it is not clear, I'll explain more.

File: test/e2e-go/features/partitionRecovery/partitionRecovery_test.go (hunk 2 above)
Comment (winder) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: Thanks for the explanation. I think there is still a race condition, here is what the test does:
```
n1 - FullStop
roundAfterStop
n1.Start
                        <--- race condition here, n1 and n2 are running
n2.FullStop
roundAfterStall
```

Comment (algonautshant) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: in theory yes, you are correct. However, this is unlikely to happen, because at this point the network is stalled, and it will take a long time for it to recover to make any progress. By the time that may happen, n2 is already stopped.

However, in the previous situation, it was possible even in a fraction of a second to change the round.

Comment (winder) [reply test/e2e-go/features/partitionRecovery/partitionRecovery_test.go:158]: I'll defer whether or not this point is blocking for the PR. Seems like we may as well stop n2 before starting n1, but maybe it isn't a problem.

**Review by winder — APPROVED** [review]
LGTM, just one minor complaint but sounds like may not be a blocker.
