### PR TITLE
config: move crash and stateproof DB defaults to hot dir

### LINKED ISSUE #5831: put agreement DB in hot storage tier
Agreement is currently in the cold storage tier, but should be in hot.

At startup, if agreement DB in cold directory (and not in hot directory), migrate file and log a warning that file was moved.

### PR DESCRIPTION
**Pull request by cce**
## Summary

This moves the crash and stateproof DBs to default to using the hot data directory. Like the ledger DB, they are frequently written while processing consensus and block updates, and are also fairly small in size, so they would benefit from being located in the hot tier.

Resolves #5831 

## Test Plan

Updated TestEnsureAndResolveGenesisDirs_hierarchy and TestConfiguredDataDirs.
Added TestEnsureAndResolveGenesisDirs_migrate and TestEnsureAndResolveGenesisDirs_migrateFail.

### CODE REVIEW

**Comment by winder** [comment]
Why?

**Review by algorandskiy — COMMENTED** [review]
I agree on the crash db move but do we really write stateproof db that often?

File: config/localTemplate.go [hunk 1]
```diff
@@ -829,27 +833,62 @@ func (cfg *Local) EnsureAndResolveGenesisDirs(rootDir, genesisID string) (Resolv
...
 		if err != nil {
 			return ResolvedGenesisDirs{}, err
 		}
 	} else {
-		resolved.StateproofGenesisDir = resolved.ColdGenesisDir
+		resolved.StateproofGenesisDir = resolved.HotGenesisDir
+		// if separate HotDataDir and ColdDataDir was configured, but StateproofDir was not configured
+		if resolved.ColdGenesisDir != resolved.HotGenesisDir {
+			// move existing stateproof DB files from ColdDataDir to HotDataDir
+			moveErr := moveDirIfExists(logger, resolved.ColdGenesisDir, resolved.HotGenesisDir, "stateproof.sqlite", "stateproof.sqlite-shm", "stateproof.sqlite-wal")
```
Comment (algorandskiy) [inline config/localTemplate.go:847]:
```suggestion
			moveErr := moveDirIfExists(logger, resolved.ColdGenesisDir, resolved.HotGenesisDir, StateProofFileName, StateProofFileName + "-shm", StateProofFileName + "-wal")
```

File: config/localTemplate.go [hunk 2]
```diff
@@ -829,27 +833,62 @@ func (cfg *Local) EnsureAndResolveGenesisDirs(rootDir, genesisID string) (Resolv
...
 		if err != nil {
 			return ResolvedGenesisDirs{}, err
 		}
 	} else {
-		resolved.CrashGenesisDir = resolved.ColdGenesisDir
+		resolved.CrashGenesisDir = resolved.HotGenesisDir
+		// if separate HotDataDir and ColdDataDir was configured, but CrashDBDir was not configured
+		if resolved.ColdGenesisDir != resolved.HotGenesisDir {
+			// move existing crash DB files from ColdDataDir to HotDataDir
+			moveErr := moveDirIfExists(logger, resolved.ColdGenesisDir, resolved.HotGenesisDir, "crash.sqlite", "crash.sqlite-shm", "crash.sqlite-wal")
```
Comment (algorandskiy) [inline config/localTemplate.go:864]:
```suggestion
			moveErr := moveDirIfExists(logger, resolved.ColdGenesisDir, resolved.HotGenesisDir, CrashFilename, CrashFilename + "-shm", CrashFilename + "-wal")
```

**Review by algorandskiy — COMMENTED** [review]
LGTM but use existing file name constants instead of literals

**Review by algorandskiy — APPROVED** [review]

File: config/config_test.go [hunk 3]
```diff
@@ -675,6 +675,12 @@ func TestEnsureAbsDir(t *testing.T) {
 	require.Equal(t, testDirectory+"/myGenesisID", t2Abs)
 }
 
+type tLogger struct{ t *testing.T }
+
+func (l tLogger) Infof(fmts string, args ...interface{}) {
+	l.t.Logf(fmts, args...)
+}
+
```
Comment (winder) [inline config/config_test.go:683]: TestingLog(tb testing.TB) in testingLogger.go is available for this

File: config/localTemplate.go [hunk 4]
```diff
@@ -771,9 +771,13 @@ func (cfg *Local) ResolveLogPaths(rootDir string) (liveLog, archive string) {
 	return liveLog, archive
 }
 
+type logger interface {
+	Infof(format string, args ...interface{})
+}
```
Comment (winder) [inline config/localTemplate.go:776]: Unless there's some sort of circular dependency, you should be able to use the existing testing logger.

File: config/localTemplate.go [hunk 5]
```diff
@@ -829,27 +833,62 @@ func (cfg *Local) EnsureAndResolveGenesisDirs(rootDir, genesisID string) (Resolv
...
+			moveErr := moveDirIfExists(logger, resolved.ColdGenesisDir, resolved.HotGenesisDir, CrashFilename, CrashFilename+"-shm", CrashFilename+"-wal")
+			if moveErr != nil {
+				return ResolvedGenesisDirs{}, fmt.Errorf("error moving crash DB files from ColdDataDir %s to HotDataDir %s: %v", resolved.ColdGenesisDir, resolved.HotGenesisDir, moveErr)
+			}
+		}
 	}
 	return resolved, nil
 }
 
+func moveDirIfExists(logger logger, srcdir, dstdir string, files ...string) error {
```
Comment (winder) [inline config/localTemplate.go:873]: nit: the name suggests that the directory is being renamed
```suggestion
func moveFilesToDirIfExists(logger logger, srcdir, dstdir string, files ...string) error {
```

**Review by winder — APPROVED** [review]
Changes look good. Left some suggestions that I think should be adopted, but don't need to block the PR.

**Review by algorandskiy — APPROVED** [review]

File: config/localTemplate.go (hunk 5 above)
Comment (algorandskiy) [reply config/localTemplate.go:873]: I'll do as a followup

File: config/config_test.go (hunk 3 above)
Comment (winder) [reply config/config_test.go:683]: Got it, thought this might be a circular dependency. Annoying.

File: config/localTemplate.go (hunk 4 above)
Comment (winder) [reply config/localTemplate.go:776]: I expect that advice isn't typically applied to cross cutting dependencies like logging. Our mistake is in customizing the logging library in algod instead of having a pure dependency.

Still. Circular dependencies are annoying and this is a good workaround.
