### PR TITLE
Goal: Fix source map mappings key and use relative line values

### LINKED ISSUE #4191: Sourcemap:  Support relative segment field values
### Subject of the issue

https://github.com/algorand/go-algorand/pull/3726 unintentionally introduced a spec mismatch.  The deviation precludes sourcemap consumers from using standard sourcemap tooling.

### Expected behaviour

The story requests implementing relative segment field values as discussed in "_The fields in each segment are:_" from https://sourcemaps.info/spec.html.

### Actual behaviour

The implementation emits absolute values rather than relative values.

### PR DESCRIPTION
**Pull request by algochoi**
## Summary

This PR deprecates the previous `mapping` field and adds the `mappings` field to align itself closer to the sourcemap specs. In addition, it fixes the mappings so that it uses relative line values for the source line mapping. 

Closes #4191 #4192 

## Test Plan

Added test to check the new field in the source map.

### CODE REVIEW

File: data/transactions/logic/sourcemap.go [hunk 1]
```diff
@@ -49,24 +51,35 @@ func GetSourceMap(sourceNames []string, offsetToLine map[int]int) SourceMap {
...
+			oldPcToLine[pc] = MakeSourceMapLine(0, 0, line, 0)
+		} else {
+			oldPcToLine[pc] = ""
+		}
+	}
+	oldEncodedMapping := strings.Join(oldPcToLine, ";")
+
+	// Array where index is the PC and value is the line for `mappings` field.
+	prevSourceLine := 0
+	pcToLine := make([]string, maxPC)
```
Comment (barnjamin) [inline data/transactions/logic/sourcemap.go:67]: The above initializer has maxPC + 1, why the difference?

Comment (algochoi) [reply data/transactions/logic/sourcemap.go]: Good catch, it should include the `maxPC` value

**Review by barnjamin — APPROVED** [review]

File: data/transactions/logic/sourcemap.go [hunk 2]
```diff
@@ -49,24 +51,35 @@ func GetSourceMap(sourceNames []string, offsetToLine map[int]int) SourceMap {
 		}
 	}
 
-	// Array where index is the PC and value is the line.
+	// Backwards compatibility for `mapping` field.
+	oldPcToLine := make([]string, maxPC+1)
+	for pc := range oldPcToLine {
+		if line, ok := offsetToLine[pc]; ok {
+			oldPcToLine[pc] = MakeSourceMapLine(0, 0, line, 0)
```
Comment (michaeldiamant) [inline data/transactions/logic/sourcemap.go:58]: @algochoi Apologies if I created confusion here - Do you agree with the thinking below?

I imagined `mapping` will be populated with a relative value rather than the absolute value.  Since the absolute line number does _not_ abide by the spec, I think we ought to fix the behavior in all places.

Comment (michaeldiamant) [reply data/transactions/logic/sourcemap.go:58]: Had a quick with @algochoi and agreed to change to _relative_ value for `mapping` rather than preserving the as was (absolute) value.

Rationale:  The prior implementation deviates from a specification.  Downstream users expect specification conformance.  Consequently, leaving as is (absolute value) precludes downstream users from using sourcemap tooling.

Leaving thread open a visual reminder until PR updates happen.

**Review by michaeldiamant — APPROVED** [review]
@algochoi Thanks for your efforts to address sourcemap spec deviations.  ☕
