### PR TITLE
AVM: Avoid panics while type checking bad immediates

### LINKED ISSUE #5217: load/store arg between -257 and 0 causes unhandled error upon compile
### Subject of the issue

Passing an arg of `load` between -256 and 0 causes aglod to throw an unhandled error when compiling. The error manifests as `ECONNRESET` when hitting the `compile` endpoint.

### Your environment

Latest sandbox on MacOS

```
12885819394
3.14.2.stable [rel/stable] (commit #8fd6e702)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand
```

### Steps to reproduce

1. Write valid TEAL program, with the exception of `load -1`
2. Send program to `/v2/compile`

https://user-images.githubusercontent.com/50534337/225974317-ce8a0772-66b7-4b40-88bd-654314159b9b.mp4

### Expected behaviour
 A 400 response with the error message `'1 error: 16: load unable to parse i "-1" as integer\n'`

### Actual behaviour
`ECONNRESET`

### PR DESCRIPTION
**Pull request by jannotti**
Added tests for immediate bounds

Fixes #5217

### CODE REVIEW

File: data/transactions/logic/assembler_test.go [hunk 1]
```diff
@@ -3267,6 +3267,34 @@ add:
...
+		Expect{1, "store i beyond 255: 256"})
+
+	testProg(t, "frame_dig -1;", AssemblerMaxVersion)
+	testProg(t, "frame_dig 127;", AssemblerMaxVersion)
+	testProg(t, "int 1; frame_bury -128;", AssemblerMaxVersion)
+
+	testProg(t, "frame_dig 128;", AssemblerMaxVersion,
+		Expect{1, "frame_dig unable to parse..."})
+	testProg(t, "int 1; frame_bury -129;", AssemblerMaxVersion,
+		Expect{1, "frame_bury unable to parse..."})
```
Comment (ahangsu) [inline data/transactions/logic/assembler_test.go:3295]: The `...` usage in `testMatch ~ testProg ~ assembler_test.go` is mindblowing...

File: data/transactions/logic/assembler.go [hunk 2]
```diff
@@ -1428,16 +1438,16 @@ func typeStores(pgm *ProgramKnowledge, args []string) (StackTypes, StackTypes, e
 }
 
 func typeLoad(pgm *ProgramKnowledge, args []string) (StackTypes, StackTypes, error) {
-	scratchIndex, ok := getImm(args, 0)
+	scratchIndex, ok := getImm(args, 0, false)
 	if !ok {
 		return nil, nil, nil
 	}
 	return nil, StackTypes{pgm.scratchSpace[scratchIndex]}, nil
```
Comment (ahangsu) [inline data/transactions/logic/assembler.go:1445]: so it seems we previously allowed people to pass in `-1` from `getImm`, and passed in `scratchSpace`, thus panic?

File: data/transactions/logic/assembler_test.go [hunk 3]
```diff
@@ -3267,6 +3267,34 @@ add:
...
+
+	testProg(t, "int 1; store 0;", AssemblerMaxVersion)
+	testProg(t, "load 255;", AssemblerMaxVersion)
+
+	testProg(t, "int 1; store -1000;", AssemblerMaxVersion,
+		Expect{1, "store unable to parse..."})
+	testProg(t, "load -100;", AssemblerMaxVersion,
+		Expect{1, "load unable to parse..."})
+	testProg(t, "int 1; store 256;", AssemblerMaxVersion,
+		Expect{1, "store i beyond 255: 256"})
```
Comment (ahangsu) [inline data/transactions/logic/assembler_test.go:3286]: I had a gap in thinking through the error message: so failing to get type info w.r.t stack won't stop you from assembling, but what really stops you is in `asmDefault` where you call `byteImm` or `int8Imm`.

Does that sounds right about code path?

**Review by ahangsu — APPROVED** [review]
lgtm, I had some question about how assembler works, but the PR itself looks right

File: data/transactions/logic/assembler.go (hunk 2 above)
Comment (jannotti) [reply data/transactions/logic/assembler.go:1445]: Yeah, I often forget how fragile the `type*` methods are. A lot of checking happens later, so I forget that these need good bounds checking on their own.  Someday, I'd like to refactor so they are a bit safer/easier to write.

File: data/transactions/logic/assembler_test.go (hunk 3 above)
Comment (jannotti) [reply data/transactions/logic/assembler_test.go:3286]: Right, because the `type*` functions bailout and usually return `nil, nil, nil` when they are confused by the immediates or the stack size. They know that the real assembly routine will be angry, so they don't need to also complain.
