### PR TITLE
REST API: Fix `LedgerStateDelta` JSON encoding

### LINKED ISSUE #6097: REST API `LedgerStateDelta.Txleases` contains invalid JSON
## Background
The `ledgercore.StateDelta.Txleases` field is defined as follows:

https://github.com/algorand/go-algorand/blob/c6a433b5035377246340710a91b295553bb6ac1f/ledger/ledgercore/statedelta.go#L103-L105

Where `Txlease` is a struct defined as:

https://github.com/algorand/go-algorand/blob/c6a433b5035377246340710a91b295553bb6ac1f/ledger/ledgercore/statedelta.go#L64-L69

## Problem
Using an object as a map key is a defined behavior for msgpack (although it does have its own complications in other languages), but JSON prohibits it. If you attempt to ask the REST API for a JSON-encoded ledger state delta, and this field is populated, the response will contain invalid JSON.

For example, this state delta,

```go
ledgercore.StateDelta{
	Txids: map[transactions.Txid]ledgercore.IncludedTransactions{
		{1, 2, 3}: {LastValid: 7, Intra: 1},
	},
	Txleases: map[ledgercore.Txlease]basics.Round{
		{Sender: basics.Address{9, 9, 9}, Lease: [32]byte{12, 13, 14}}: 8,
	},
}
```

encodes to this invalid JSON:

```json
{
  "Accts": {
    "Accts": null,
    "AppResources": null,
    "AssetResources": null
  },
  "Creatables": null,
  "Hdr": null,
  "KvMods": null,
  "PrevTimestamp": 0,
  "StateProofNext": 0,
  "Totals": {},
  "Txids": {
    "AQIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=": {
      "Intra": 1,
      "LastValid": 7
    }
  },
  "Txleases": {
    {
  "Lease": "DA0OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "Sender": "BEEQSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSLODMM"
}: 8
  }
}
```

## Solution

A possible solution is to create a variant of the `ledgercore.StateDelta` struct designed to be JSON serialized, perhaps by transforming the `Txleases` map into an array.

### PR DESCRIPTION
**Pull request by jasonpaulos**
## Summary

Removes the `Txleases` field from JSON state delta representations, as this field cannot be properly JSON encoded.

Based on #6100

Closes #6097

## Test Plan

Test coverage added on all 3 endpoints.

### CODE REVIEW

File: daemon/algod/api/server/v2/handlers.go [hunk 1]
```diff
@@ -1420,6 +1420,25 @@ func (v2 *Handlers) GetSyncRound(ctx echo.Context) error {
 	return ctx.JSON(http.StatusOK, model.GetSyncRoundResponse{Round: rnd})
 }
 
+// TxleaseSerializable is used by LedgerStateDeltaJSONSerializable to represent the Txleases map
+type TxleasJSONSerializable struct {
```
Comment (jannotti) [inline daemon/algod/api/server/v2/handlers.go:1424]:
```suggestion
// TxleaseSerializable is used by LedgerStateDeltaJSONSerializable to represent the Txleases map
type TxleaseJSONSerializable struct {
```

Comment (jasonpaulos) [reply daemon/algod/api/server/v2/handlers.go]: 2eb5fb10b

File: daemon/algod/api/server/v2/utils.go [hunk 2]
```diff
@@ -626,6 +627,49 @@ func convertSimulationRequest(request PreEncodedSimulateRequest) simulation.Requ
...
+func convertLedgerStateDelta(sd ledgercore.StateDelta) LedgerStateDeltaJSONSerializable {
+	serializableTxleases := make([]TxleaseJSONSerializable, 0, len(sd.Txleases))
+	for k, v := range sd.Txleases {
+		serializableTxleases = append(serializableTxleases, TxleaseJSONSerializable{
+			Sender:     k.Sender,
+			Lease:      k.Lease,
+			Expiration: v,
+		})
+	}
+	// TODO: sort for deterministic response
```
Comment (Ashy5000) [inline daemon/algod/api/server/v2/utils.go:639]: What would it be sorted based on? Maybe each `Txlease` is hashed and the digests are compared? Or they could be formatted with `%+v` and then ordered based on the resulting strings? The latter would probably be faster.

Comment (jasonpaulos) [reply daemon/algod/api/server/v2/utils.go]: Added in 361d1c6

File: data/transactions/transaction.go [hunk 3]
```diff
@@ -38,9 +38,9 @@ func (txid Txid) String() string {
 	return fmt.Sprintf("%v", crypto.Digest(txid))
 }
 
-// UnmarshalText initializes the Address from an array of bytes.
-func (txid *Txid) UnmarshalText(text []byte) error {
```
Comment (jasonpaulos) [inline data/transactions/transaction.go:42]: I had to rename `Txid.UnmarshalText` because it led to asymmetrical treatment in encoding and decoding.

Prior to this PR, JSON encoding a `Txid` object would result in a base64-encoded byte array, but our decoder would use this `UnmarshalText` method, which only works for a base32-encoded string.

I fixed this by renaming the method so now decoding will work from a base64-encoded byte array.

File: daemon/algod/api/client/restClient.go [hunk 4]
```diff
@@ -229,7 +230,7 @@ func (client RestClient) submitForm(
 	}
 
 	if decodeJSON {
-		dec := json.NewDecoder(resp.Body)
+		dec := protocol.NewJSONDecoder(resp.Body)
```
Comment (jasonpaulos) [inline daemon/algod/api/client/restClient.go:233]: Changed `RestClient` to use the `protocol` package's JSON decoding instead of the default Go `json` package's.

The default `json` package does not support our codec tags enough to successfully decode state deltas (which are rather complex). Besides, we encode all REST responses with `protocol`, so it only makes sense to be consistent here.

File: daemon/algod/api/client/restClient.go [hunk 5]
```diff
@@ -559,7 +560,9 @@ func (client RestClient) SendRawTransactionGroup(txgroup []transactions.SignedTx
 }
 
 // Block gets the block info for the given round
-func (client RestClient) Block(round uint64) (response model.BlockResponse, err error) {
+func (client RestClient) Block(round uint64) (response v2.BlockResponseJSON, err error) {
```
Comment (jasonpaulos) [inline daemon/algod/api/client/restClient.go:563]: For `Block` and the other state delta endpoints, I opted to decode the responses into the struct types that are used for encoding in `daemon/algod/api/server/v2/handlers.go`. Otherwise these objects are thin wrappers around `map[string]interface{}`, which is not as useful.

File: daemon/algod/api/server/v2/handlers.go [hunk 6]
```diff
@@ -2003,6 +2031,31 @@ func (v2 *Handlers) TealDisassemble(ctx echo.Context) error {
...
+// instead an array.
+type LedgerStateDeltaSubsetJSONSerializable struct {
+	eval.StateDeltaSubset
+
+	// A serialized version of the eval.StateDeltaSubset.Txleases map
+	Txleases []TxleaseJSONSerializable
+}
+
+// TxnGroupDeltaWithIDsJSONSerializable is a version of eval.TxnGroupDeltaWithIds
+// that able to be serialized to valid JSON.
```
Comment (jannotti) [inline daemon/algod/api/server/v2/handlers.go:2047]:
```suggestion
// TxnGroupDeltaWithIDsJSONSerializable is a version of eval.TxnGroupDeltaWithIds
// that can be serialized to valid JSON.
```

**Review by jannotti — APPROVED** [review]
This looks like a fine fix to make sure the leases can be emitted as valid JSON.  On the other hand, I'm struggling to see any value in sending the lease information at all, since it is very explicit already in the transaction (the sender, the lease, and the implied expiration from last valid).
Anyway, I'm ok with this, or zeroing the leases map before creating JSON.

File: daemon/algod/api/server/v2/handlers.go (hunk 6 above)
Comment (jasonpaulos) [reply daemon/algod/api/server/v2/handlers.go]: Fixed in b4c548529

File: data/transactions/transaction.go (hunk 3 above)
Comment (jasonpaulos) [reply data/transactions/transaction.go:42]: No, the encoder must not look at the `.String()` method.  This produces base64 bytes:
```go
var txid transactions.Txid
bytes := protocol.EncodeJSONStrict(&txid)
fmt.Printf("txid bytes: %s", string(bytes)) // produces "txid bytes: \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\""
```

Comment (algorandskiy) [reply data/transactions/transaction.go:42]: does not look like this: if not special marshal methods then it array is encoded as json array:

> Marshal traverses the value v recursively. If an encountered value implements [Marshaler](https://pkg.go.dev/encoding/json@go1.23.0#Marshaler) and is not a nil pointer, Marshal calls [Marshaler.MarshalJSON] to produce JSON. If no [Marshaler.MarshalJSON] method is present but the value implements [encoding.TextMarshaler](https://pkg.go.dev/encoding#TextMarshaler) instead, Marshal calls [encoding.TextMarshaler.MarshalText](https://pkg.go.dev/encoding#TextMarshaler.MarshalText) and encodes the result as a JSON string. The nil pointer exception is not strictly necessary but mimics a similar, necessary exception in the behavior of [Unmarshaler.UnmarshalJSON].
> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.

It also does not match what Jason mentioned:
>JSON encoding a Txid object would result in a base64-encoded byte array,

Something to look into I guess

Comment (algorandskiy) [reply data/transactions/transaction.go:42]: ah, it is codec, not `encoding/json`, ok.

**Review by jannotti — APPROVED** [review]

File: daemon/algod/api/server/v2/handlers.go [hunk 7]
```diff
@@ -2044,10 +2103,19 @@ func (v2 *Handlers) GetTransactionGroupLedgerStateDeltasForRound(ctx echo.Contex
...
-	}{
-		Deltas: deltas,
+	var response interface{}
+	if handle == protocol.JSONStrictHandle {
+		response = struct {
+			Deltas []TxnGroupDeltaWithIDsJSONSerializable
+		}{
+			Deltas: convertTxnGroupDeltasWithIDs(deltas),
+		}
+	} else {
```
Comment (gmalouf) [inline daemon/algod/api/server/v2/handlers.go:2113]: is there a test case to be added for this?

File: daemon/algod/api/server/v2/utils.go [hunk 8]
```diff
@@ -626,6 +628,68 @@ func convertSimulationRequest(request PreEncodedSimulateRequest) simulation.Requ
 	}
 }
 
+// sortTxleaseJSONSerializableSlice lexicographically sorts a slice of TxleaseJSONSerializable
+func sortTxleaseJSONSerializableSlice(s []TxleaseJSONSerializable) {
```
Comment (gmalouf) [inline daemon/algod/api/server/v2/utils.go:632]: Are these actually not covered or are we relying on the devmode tests to cover?

**Review by gmalouf — APPROVED** [review]

File: daemon/algod/api/server/v2/utils.go (hunk 8 above)
Comment (jasonpaulos) [reply daemon/algod/api/server/v2/utils.go]: No longer relevant due to 2621ac8

File: daemon/algod/api/server/v2/handlers.go (hunk 7 above)
Comment (jasonpaulos) [reply daemon/algod/api/server/v2/handlers.go]: Yes, the modified e2e tests check the JSON output

**Review by gmalouf — APPROVED** [review]

File: daemon/algod/api/server/v2/handlers.go [hunk 9]
```diff
@@ -1432,6 +1435,11 @@ func (v2 *Handlers) GetLedgerStateDelta(ctx echo.Context, round uint64, params m
 	if err != nil {
 		return notFound(ctx, err, fmt.Sprintf(errFailedRetrievingStateDelta, err), v2.Log)
 	}
+	if handle == protocol.JSONStrictHandle {
+		// Zero out the Txleases map since it cannot be represented in JSON, as it is a map with an
+		// object key.
```
Comment (jannotti) [inline daemon/algod/api/server/v2/handlers.go:1440]:
```suggestion
		// Zero out the Txleases map since it cannot be represented in JSON, as it is a map with an
		// object key. The information is readily available from the transaction themselves.
```

**Review by jannotti — APPROVED** [review]

File: daemon/algod/api/server/v2/handlers.go (hunk 9 above)
Comment (jasonpaulos) [reply daemon/algod/api/server/v2/handlers.go:1440]: Good improvement but I don't want to dismiss the two approvals for this (and because flakey tests are particularly bad right now...)
